### ISSUE TITLE
Two batteries

### ISSUE THREAD

**Issue by emersons** [Icenowy/axpd#2]
Hi,

Before I run this script I have a false battery detected which always has 100% charge. When I run this script, my battery is correctly added to the power icon in the menu bar and the correct charge is outputted in the terminal. However, the command 'rmmod battery' fails and I am left with two batteries.

As you can see in this [picture](http://imgur.com/FMzVHhR), when my charge is at 80%, it is reported as 90% in the menu because it thinks there are two batteries present.

Is there some way to remove the false battery?

**Comment by Icenowy** [comment]
maybe you'd blacklist some modules... I don't know it... :-(
2016年5月20日 13:49于 emersons notifications@github.com写道：Hi,

Before I run this script I have a false battery detected which always has 100% charge. When I run this script, my battery is correctly added to the power icon in the menu bar and the correct charge is outputted in the terminal. However, the command 'rmmod battery' fails and I am left with two batteries.

As you can see in this picture, when my charge is at 80%, it is reported as 90% in the menu because it thinks there are two batteries present.

Is there some way to remove the false battery?

**Comment by emersons** [comment]
Oh. It happens in the mainline kernel 4.4.0, on a fresh install. Which one do you use?

When I run 'sudo rmmod battery' I get the output 'rmmod: ERROR: Module battery is builtin'. I suspect this is the issue as an inbuilt module cannot be removed.

**Comment by Icenowy** [comment]
what distro are you using... you may need to rebuild your kernel...
2016年5月20日 13:57于 emersons notifications@github.com写道：Oh. It happens in the mainline kernel 4.4.0, on a fresh install. Which one do you use?

When I run 'sudo rmmod battery' I get the output 'rmmod: ERROR: Module battery is builtin'. I suspect this is the issue as an inbuilt module cannot be removed.

**Comment by emersons** [comment]
Ubuntu 16.04, 64bit. I have tried the 4.1.12 and 4.6.0 kernels too and I get the same issue. Which one do you use? I could try that and make sure it is not my hardware, although I have a baytrail too.

**Comment by Icenowy** [comment]
I used to use a special .config file on my Teclast X98 Air 3G when the kernel version is still 4.2. Now I abandoned to hack Baytrail, and this tablet now runs Android. (I'm hacking Allwinner now)
2016年5月20日 14:08于 emersons notifications@github.com写道：Ubuntu 16.04, 64bit. I have tried the 4.1.12 and 4.6.0 kernels too and I get the same issue. Which one do you use? I could try that and make sure it is not my hardware, although I have a baytrail too.

**Comment by emersons** [comment]
Can you share this config file please, if you still have it?
